.TH hefesto 1 "September 11, 2016" "version 0.1.1" "USER COMMANDS"
.SH NAME
hefesto \- a multi platform build tool
.SH SYNOPSIS
.B hefesto [\fIOPTIONS\fR]
.SH DESCRIPTION
The main Hefesto's feature is allow a more programatic build scripting.
.PP
In order to do it Hefesto uses his own language (more procedural than declarative).
.PP
Seeking:
.TP
.PP
\- Clarity

\- Organization

\- Expansibility
.PP
This application can help not only a small amount of programmers which use some specific languages and toolsets, Hefesto helps on automation of several tasks that go beyond just compiling and linking programs. It depends on your necessity and disposition to extend the Hefesto.
.PP
When you extend Hefesto this does not mean that you need to recompile the application. All is done via Hsl, the domain specific language which Hefesto implements.
.PP
The \fIHSL\fR was developed to be simple but robust.
.SH OPTIONS
.TP
\-\-forgefiles=\fIfoo.hsl,bar.hsl\fR
Indicates the Forgefiles paths which contains the projects.

Note that to build fooproject defined inside "foo.hsl" you must
use the dynamic option "\-\-foo\-projects=fooproject" in this case.
.TP
\-\-compile\-only
Performs the basic compilation of files supplied by "\-\-forgefiles" option.
.TP
\-\-forge-anyway
Compiles all project source files ignoring the change status.
.TP
\-\-qsize=\fIn\fR
Configures the size of work queue.
.TP
\-\-user\-includes\-home=\fI"~/myincs","/etc/incs"\fR
Defines additional includes search paths.
.TP
\-\-version
Displays the application version.
.PP
.SH EXIT STATUS
If all build task succeeds hefesto returns zero, otherwise
non zero value will be returned.
.PP
.SH
SEE ALSO
.TP
\fI/usr/local/share/hefesto/doc\fR (or equivalent on your system)
.PP
.SH
HOMEPAGE
.TP
https://github.com/rafael-santiago/hefesto
.SH AUTHOR
Rafael Santiago <voidbrainvoid@gmail.com>
